### ISSUE TITLE
appveyor のビルド完了を GitHub 上で通知したい

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#957]
## 要望機能
appveyor のビルド完了を GitHub 上で通知したい

## 背景

vswhere のリポジトリを見ると https://github.com/microsoft/vswhere/pull/110#issuecomment-334968177 の感じで、appveyor のビルド完了を AppVeyorBot のアカウントで通知している。

調査すると
https://www.appveyor.com/docs/notifications/#github-pull-request にあるように

appveyor.yml に以下のような感じで書くと、GitHub に自動的に通知を書いてくれるみたい。
(まだ実験はしてないです)

```
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: kBl9BlxvRMr9liHmnBs14A==
    template: "{{#passed}}:white_check_mark"
```

**追記: appveyor の GUI 画面で設定可能です。**

## 利点

ビルドが成功しているか一目瞭然になる。

## 欠点

いっぱいビルドすると、いっぱい AppVeyorBot の通知が来てうっとおしいかも。
